#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_servo_on_off.servo_on_off import ServoOnOff


def main():
    main = Main()
    sys.exit(main.main(sys.argv, standalone='rqt_servo_on_off.servo_on_off.ServoOnOff'))


if __name__ == '__main__':
    main()
